#!/bin/bash
BASEDIR="$(dirname "$BASH_SOURCE")"
cd "$BASEDIR"
if (( $EUID != 0 )); then
    printf "\n-----Sorry! Run with root privilege\n\n"
    exit 1
fi
make uninstall
make clean || echo "You can ignore 'make clean' error"
